version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: arquiz-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: arquiz
      POSTGRES_PASSWORD: arquiz
      POSTGRES_DB: arquiz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arquiz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - arquiz-network

  redis:
    image: redis:7-alpine
    container_name: arquiz-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - arquiz-network

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: arquiz-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: arquiz
      RABBITMQ_DEFAULT_PASS: arquiz
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - arquiz-network

networks:
  arquiz-network:
    driver: bridge

volumes:
  postgres_data:
    name: arquiz-postgres-data
  redis_data:
    name: arquiz-redis-data
  rabbitmq_data:
    name: arquiz-rabbitmq-data 